### ISSUE TITLE
FancyVideo API has failed to load correctly

### ISSUE THREAD

**Issue by PurplyPlus** [Nick1st/FancyVideo-API#8]
---- Minecraft Crash Report ----
// There are four lights!

Time: 01/06/23 21:20
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:174) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9486/119423135.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9242/280226418.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:memoryleakfix-16.mixins.json:targetEntityLeak.Minecraft_targetClearMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$496/1453650546.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.newLibVlcInstance(MediaPlayerFactory.java:214) ~[?:1.16.5-0.1.1.1-beta] {re:classloading}
-- MOD fancyvideo-api --
Details:
	Mod File: FancyVideo-API-1.16.5-2.2.0.3.jar
	Failure message: FancyVideo API (fancyvideo-api) has failed to load correctly
		java.lang.RuntimeException: Failed to get a new native library instance
	Mod Version: 2.2.0.3
	Mod Issue URL: https://github.com/Nick1st/FancyVideo-API/issues
	Exception message: java.lang.RuntimeException: Failed to get a new native library instance
Stacktrace:
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.newLibVlcInstance(MediaPlayerFactory.java:214) ~[?:1.16.5-0.1.1.1-beta] {re:classloading}
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:110) ~[?:1.16.5-0.1.1.1-beta] {re:classloading}
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132) ~[?:1.16.5-0.1.1.1-beta] {re:classloading}
	at nick1st.fancyvideo.api.MediaPlayerHandler.getInstance(MediaPlayerHandler.java:58) ~[?:1.16.5-0.1.1.1-beta] {re:classloading}
	at nick1st.fancyvideo.ShutdownHook.<init>(ShutdownHook.java:7) ~[?:1.16.5-0.1.1.1-beta] {re:classloading}
	at nick1st.fancyvideo.CommonMainClass.<init>(CommonMainClass.java:60) ~[?:1.16.5-0.1.1.1-beta] {re:classloading}
	at nick1st.fancyvideo.FancyVideoAPI.<init>(FancyVideoAPI.java:88) ~[?:1.16.5-0.1.1.1-beta] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3174/231870140.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3449/967337409.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2218757936 bytes (2115 MB) / 4060086272 bytes (3872 MB) up to 5335154688 bytes (5088 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx5078M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		FusinSVM.jar                                      |FusinSVM                      |fusinsvm                      |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		player-animation-lib-forge-0.4.0+1.16.5.jar       |Player Animator               |playeranimator                |0.4.0+1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		jei-1.16.5-7.8.0.1009.jar                         |Just Enough Items             |jei                           |7.8.0.1009          |CREATE_REG|Manifest: NOSIGNATURE
		HealthOverlay-1.16.5-3.0.1.jar                    |Health Overlay                |healthoverlay                 |3.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		AttributeFix-1.16.5-10.1.4.jar                    |AttributeFix                  |attributefix                  |10.1.4              |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		connectivity-2.4-1.16.5.jar                       |Connectivity Mod              |connectivity                  |2.4-1.16.5          |CREATE_REG|Manifest: NOSIGNATURE
		modnametooltip_1.16.2-1.15.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.15.0              |CREATE_REG|Manifest: NOSIGNATURE
		InsaneLib-1.4.2-mc1.16.5.jar                      |InsaneLib                     |insanelib                     |1.4.2               |CREATE_REG|Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |CREATE_REG|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |CREATE_REG|Manifest: NOSIGNATURE
		Clumps-6.0.0.28.jar                               |Clumps                        |clumps                        |6.0.0.28            |CREATE_REG|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p6.jar                     |Journeymap                    |journeymap                    |5.8.5p6             |CREATE_REG|Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |CREATE_REG|Manifest: NOSIGNATURE
		Controlling-7.0.0.29.jar                          |Controlling                   |controlling                   |7.0.0.29            |CREATE_REG|Manifest: NOSIGNATURE
		modernlife-1.16.5-1.51.jar                        |Modern Life                   |modernlife                    |1.16.5-1.51         |CREATE_REG|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |CREATE_REG|Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |CREATE_REG|Manifest: NOSIGNATURE
		Artifacts-1.16.5-2.10.5.jar                       |Artifacts                     |artifacts                     |1.16.5-2.10.5       |CREATE_REG|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |CREATE_REG|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.33.jar                |Bookshelf                     |bookshelf                     |10.4.33             |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.16.5-3.15.20.755.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.15.20.755  |CREATE_REG|Manifest: NOSIGNATURE
		mcw-doors-1.0.9forge-mc1.16.5.jar                 |Macaw's Doors                 |mcwdoors                      |1.0.9               |CREATE_REG|Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |CREATE_REG|Manifest: NOSIGNATURE
		inventorypets-1.16.5-2.0.15.jar                   |Inventory Pets                |inventorypets                 |2.0.15              |CREATE_REG|Manifest: NOSIGNATURE
		VideoPlayer-0.5-BETA-1.16.5.jar                   |VideoPlayer                   |videoplayer                   |0.5                 |CREATE_REG|Manifest: NOSIGNATURE
		memoryleakfix-forge-pre1.17-1.0.0.jar             |Memory Leak Fix               |memoryleakfix                 |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.133.jar         |Just Enough Resources         |jeresources                   |0.12.1.133          |CREATE_REG|Manifest: NOSIGNATURE
		Paraglider-1.16.5-1.3.2.14.jar                    |Paraglider                    |paraglider                    |1.3.2.14            |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tl_skin_cape_forge_1.16.5-1.19.jar                |TLSkinCape                    |tlskincape                    |1.19                |CREATE_REG|Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		supplementaries-1.16.5-0.18.5.jar                 |Supplementaries               |supplementaries               |0.18.2              |CREATE_REG|Manifest: NOSIGNATURE
		betterendforge-1.16.5-2.5.jar                     |BetterEnd Forge               |betterendforge                |1.16.5-2.5          |CREATE_REG|Manifest: NOSIGNATURE
		emotecraft-for-MC1.16.5-2.2.5-forge.jar           |Emotecraft                    |emotecraft                    |2.2.5               |CREATE_REG|Manifest: NOSIGNATURE
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |CREATE_REG|Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |CREATE_REG|Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.49-beta.jar              |When Dungeons Arise           |dungeons_arise                |2.1.49              |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		TenshiLib-1.16.3-1.3.0.jar                        |TenshiLib                     |tenshilib                     |1.16.3-1.3.0        |CREATE_REG|Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.6.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.6.0        |CREATE_REG|Manifest: NOSIGNATURE
		torchmaster-2.3.8.jar                             |Torchmaster                   |torchmaster                   |2.3.8               |CREATE_REG|Manifest: NOSIGNATURE
		voicechat-forge-1.16.5-2.4.5.jar                  |Simple Voice Chat             |voicechat                     |1.16.5-2.4.5        |CREATE_REG|Manifest: NOSIGNATURE
		EasierSleeping-1.16.5-2.0.0.jar                   |Easier Sleeping               |easier_sleeping               |2.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		silent-lib-1.16.5-4.10.0.jar                      |Silent Lib                    |silentlib                     |4.10.0              |CREATE_REG|Manifest: NOSIGNATURE
		getittogetherdrops-1.16.5-v1.2.jar                |Get It Together, Drops!       |getittogetherdrops            |1.16.5-v1.2         |CREATE_REG|Manifest: NOSIGNATURE
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.16.5forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |CREATE_REG|Manifest: NOSIGNATURE
		silent-gear-1.16.5-2.6.36.jar                     |Silent Gear                   |silentgear                    |2.6.36              |CREATE_REG|Manifest: NOSIGNATURE
		invocore-1.16.5-1.6.0.jar                         |Invocore                      |invocore                      |1.6.0               |CREATE_REG|Manifest: NOSIGNATURE
		betterfpsdist-1.2.jar                             |betterfpsdist mod             |betterfpsdist                 |1.2                 |CREATE_REG|Manifest: NOSIGNATURE
		lightspeed-1.16.5-1.0.2.jar                       |Lightspeed                    |lightspeed                    |1.16.5-1.0.2        |CREATE_REG|Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |CREATE_REG|Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |CREATE_REG|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.1.0.0.jar                   |Curios API                    |curios                        |1.16.5-4.1.0.0      |CREATE_REG|Manifest: NOSIGNATURE
		Croptopia-1.16.5-FORGE-2.0.5.jar                  |Croptopia                     |croptopia                     |2.0.5               |CREATE_REG|Manifest: NOSIGNATURE
		collective-1.16.5-5.49.jar                        |Collective                    |collective                    |5.49                |CREATE_REG|Manifest: NOSIGNATURE
		camera-1.16.5-1.0.14.jar                          |Camera Mod                    |camera                        |1.16.5-1.0.14       |CREATE_REG|Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.41.jar                   |Polymorph                     |polymorph                     |1.16.5-0.41         |CREATE_REG|Manifest: NOSIGNATURE
		[1.16.5] SecurityCraft v1.9.6.1.jar               |SecurityCraft                 |securitycraft                 |v1.9.6.1            |CREATE_REG|Manifest: NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |CREATE_REG|Manifest: NOSIGNATURE
		obfuscate-0.6.3-1.16.5.jar                        |Obfuscate                     |obfuscate                     |0.6.3               |CREATE_REG|Manifest: NOSIGNATURE
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |CREATE_REG|Manifest: NOSIGNATURE
		morevanillaarmor-1.16.4-1.2.6.jar                 |MoreVanillaArmor              |morevanillaarmor              |1.16.4-1.2.6        |CREATE_REG|Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.4.0.jar                |AppleSkin                     |appleskin                     |2.4.0+mc1.16.4      |CREATE_REG|Manifest: NOSIGNATURE
		Theft-1.3.jar                                     |Theft                         |theft                         |1.2                 |CREATE_REG|Manifest: NOSIGNATURE
		lootr-1.16.5-0.2.17.48.jar                        |Lootr                         |lootr                         |0.1.15.46           |CREATE_REG|Manifest: NOSIGNATURE
		Chisel-MC1.16.5-2.0.1-alpha.4.jar                 |Chisel                        |chisel                        |MC1.16.5-2.0.1-alpha|CREATE_REG|Manifest: NOSIGNATURE
		AI-Improvements-1.16.5-0.5.0.jar                  |AI-Improvements               |aiimprovements                |0.4.0               |CREATE_REG|Manifest: NOSIGNATURE
		mcw-furniture-3.1.0-mc1.16.5forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		SoL-Carrot-1.16.5-1.10.1.jar                      |Spice of Life: Carrot Edition |solcarrot                     |1.16.5-1.10.1       |CREATE_REG|Manifest: NOSIGNATURE
		improvedmobs-1.16.5-1.10.13.jar                   |Improved Mobs Mod             |improvedmobs                  |1.16.5-1.10.13      |CREATE_REG|Manifest: NOSIGNATURE
		expandability-2.0.1-forge.jar                     |ExpandAbility                 |expandability                 |2.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v5.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v5           |CREATE_REG|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		CodeChickenLib-1.16.5-4.0.7.445-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.7.445           |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.16.5-2.8.0.170-universal.jar       |EnderStorage                  |enderstorage                  |2.8.0.170           |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		PlayerRevive_v2.0.0-pre04_mc1.16.5.jar            |PlayerRevive                  |playerrevive                  |2.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		mcw-lights-1.0.5-mc1.16.5forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.5               |CREATE_REG|Manifest: NOSIGNATURE
		FancyVideo-API-1.16.5-2.2.0.3.jar                 |FancyVideo API                |fancyvideo-api                |2.2.0.3             |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: bd3e211e-b501-4032-9c6c-8c42a17a7c80
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre2
	OptiFine Build: 20210305-002749
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 22.20.27.09.230330
	OpenGlRenderer: Radeon RX 570 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by Brun010** [comment]
"failed to load correctly" might mean that there is a problem with the instance, but i am no java expert.
i got this message after updating a modpack to a newer version, so it might be cause by some residue.
conclusion: after trying a lot of thing i re-installed the instance and forge version, after that i picked only my worlds folder and put into the new instance, and it woked.
That worked for me but your issue might be different.

**Comment by Nick1st** [comment]
# FancyVideo-API - Notice of Discontinuance
As of today, Friday, Feburary the 12th 2024 **FancyVideo-API is officially discontinued immediately**. I'm deeply sorry for all inconveniences this causes.

## Why?
I didn't make this decision light-hearted. FV-API started as a research and tech demo project. As such, the project wasn't well planed, the tech used by it was a bunch of buggy hacks, held together by loose amounts of duct-tape. That luckily got better within the first versions, however the API did never reach a level that I was satisfied with. Because of that I started a rewrite about one years ago, but due to a series of unlucky events this project stalled. Despite simply forward porting the legacy API would've been a task of hours, I decided against it. During the rewrite I was beaten time and time again to the conclusion that several layers of the API were flawed from the grounds up. That further stalled progress, and also was the reason why I didn't simply continue forward porting. During the two years I maintained FV-API, I got a much better understanding of how things work, and how they should've be done instead. 
FV-API started as a tech demo/research project and I must admit that that's all it ever was. With the knowledge I have today, I probably wouldn't have published the project on CurseForge for others to use, the project was not ready for that (nor meant for it in the beginning). I think FV still reached the goal it was originally  created for: showing whats technically possible and getting others to build upon the idea.

## What does this mean?
FV-API will no longer receive updates (This includes critical bugfixes and security updates). If you're using FV-API as a library, you should move on (simply read on for more details).

## What should I do (Modder)
I do not want to recommend a specific project, however here are two projects that I came along over the last year:
- [WATERMeDIA: Multimedia API](https://www.curseforge.com/minecraft/mc-mods/watermedia) by SrRapero720
- [A fork](https://github.com/BehindTheScenery/FancyVideo-API) by BehindTheScenery

## What's going to happen with this discord server?
I'll put this server in read-only mode until there is something new from me.
I'm still interested in the project, and I've recently been obsessed with Gstreamer. Maybe one day there will be FV-2.0 (probably as a tech demo only though!).


I just want to thank everybody who used FV-API over the last two years. I should've probably done this step half a year earlier, but I just wanted to (personally) feel sure that this is the right decision. I simply do no longer have the time required to maintain this project due to things that changed in my personal life. Thanks again for using FV-API. I hope you all stay well.
