### ISSUE TITLE
Failing to load VLC under Linux

### ISSUE THREAD

**Issue by oxodao** [Nick1st/FancyVideo-API#9]
Hey,
I'm having an issue under Linux where it crashes as soon as I open the the world.
My guess is that my VLC version is not the correct one, but according to the code ([here](https://github.com/Nick1st/FancyVideo-API/blob/989e11dd27a07025dddc37d349a9860fcb4fe4a0/src/main/java/nick1st/fancyvideo/FancyVideo.java.dis#L178)), you're already ensuring that the version is correct.

Pretty sure this is not an issue related to waterframes so I posted it here, sorry otherwise

Here's the relevant logs:
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.LibVlc
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.tryLoadingLibrary(NativeDiscovery.java:187) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.discover(NativeDiscovery.java:118) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:176) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.player.component.CallbackMediaPlayerComponent.initMediaPlayerFactory(CallbackMediaPlayerComponent.java:238) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.player.component.CallbackMediaPlayerComponent.<init>(CallbackMediaPlayerComponent.java:129) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.player.component.CallbackMediaPlayerComponent.<init>(CallbackMediaPlayerComponent.java:190) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at me.srrapero720.waterframes.display.MediaDisplay.<init>(MediaDisplay.java:83) ~[WATERFrAMES-1.18.2-1.2.0c.jar%23151!/:1.18.2-1.2.0c] {re:classloading}
	at me.srrapero720.waterframes.display.MediaDisplay.lambda$createVideoDisplay$0(MediaDisplay.java:52) ~[WATERFrAMES-1.18.2-1.2.0c.jar%23151!/:1.18.2-1.2.0c] {re:classloading}
	at me.srrapero720.waterframes.watercore_supplier.ThreadUtil.tryAndReturn(ThreadUtil.java:24) ~[WATERFrAMES-1.18.2-1.2.0c.jar%23151!/:1.18.2-1.2.0c] {re:classloading}
	at me.srrapero720.waterframes.watercore_supplier.ThreadUtil.tryAndReturn(ThreadUtil.java:19) ~[WATERFrAMES-1.18.2-1.2.0c.jar%23151!/:1.18.2-1.2.0c] {re:classloading}
	at me.srrapero720.waterframes.watercore_supplier.ThreadUtil.tryAndReturn(ThreadUtil.java:15) ~[WATERFrAMES-1.18.2-1.2.0c.jar%23151!/:1.18.2-1.2.0c] {re:classloading}
	at me.srrapero720.waterframes.display.MediaDisplay.createVideoDisplay(MediaDisplay.java:51) ~[WATERFrAMES-1.18.2-1.2.0c.jar%23151!/:1.18.2-1.2.0c] {re:classloading}
	at me.srrapero720.waterframes.display.texture.TextureCache.createDisplay(TextureCache.java:127) ~[WATERFrAMES-1.18.2-1.2.0c.jar%23151!/:1.18.2-1.2.0c] {re:mixin,re:classloading}
	at me.srrapero720.waterframes.display.texture.TextureCache.createDisplay(TextureCache.java:122) ~[WATERFrAMES-1.18.2-1.2.0c.jar%23151!/:1.18.2-1.2.0c] {re:mixin,re:classloading}
	at me.srrapero720.waterframes.custom.blocks.TileFrame.requestDisplay(TileFrame.java:111) ~[WATERFrAMES-1.18.2-1.2.0c.jar%23151!/:1.18.2-1.2.0c] {re:classloading}
	at me.srrapero720.waterframes.custom.blocks.TileFrame.tick(TileFrame.java:232) ~[WATERFrAMES-1.18.2-1.2.0c.jar%23151!/:1.18.2-1.2.0c] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%23157!/:?] {re:classloading}
	... 20 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Error looking up function 'libvlc_media_get_filestat': /usr/lib64/libvlc.so: undefined symbol: libvlc_media_get_filestat [in thread "modloading-worker-0"]
	at com.sun.jna.Function.<init>(Function.java:252) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.register(Native.java:1904) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.register(Native.java:1775) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.register(Native.java:1493) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:129) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.tryLoadingLibrary(NativeDiscovery.java:187) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.discover(NativeDiscovery.java:118) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at nick1st.fancyvideo.CommonMainClass.discoverNativeVLC(CommonMainClass.java:133) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at nick1st.fancyvideo.CommonMainClass.onInit(CommonMainClass.java:122) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at nick1st.fancyvideo.CommonMainClass.<init>(CommonMainClass.java:80) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at nick1st.fancyvideo.FancyVideoAPI.<init>(FancyVideoAPI.java:86) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.4.jar%23159!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.4.jar%23158!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

EDIT: It seems that the related method had its name changed ([related VLC issue](https://code.videolan.org/videolan/vlc/-/issues/26475)) but its not in the VLC 3.x package that is available in the archlinux repositories. I'll try with `vlc-git` that seems to be 4.x

Edit2:
Using `vlc-git` still doesn't work, but it crashes on an other method:
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Error looking up function 'libvlc_media_parse_with_options': /usr/lib64/libvlc.so: undefined symbol: libvlc_media_parse_with_options [in thread "modloading-worker-0"]
	at com.sun.jna.Function.<init>(Function.java:252) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.register(Native.java:1904) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.register(Native.java:1775) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.register(Native.java:1493) ~[jna-5.10.0.jar%2360!/:5.10.0 (b0)] {}
	at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:129) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.tryLoadingLibrary(NativeDiscovery.java:187) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.discover(NativeDiscovery.java:118) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at nick1st.fancyvideo.CommonMainClass.discoverNativeVLC(CommonMainClass.java:133) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at nick1st.fancyvideo.CommonMainClass.onInit(CommonMainClass.java:122) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at nick1st.fancyvideo.CommonMainClass.<init>(CommonMainClass.java:80) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at nick1st.fancyvideo.FancyVideoAPI.<init>(FancyVideoAPI.java:86) ~[FancyVideo-API-forge-2.2.0.0.jar%2394!/:2.2.0.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.4.jar%23159!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.4.jar%23158!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
[14:18:50] [Thread-19/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?] {}
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?] {}
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?] {}
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-1.0.8.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-1.0.8.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-1.0.8.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-1.0.8.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.8.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:95) ~[?:?] {re:classloading}
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2348!/:build 10] {}
```

Would it be possible to have a config to select manually the path for the library (because FVA seems to load the system one first), and the correct `.so` from version that you're using for Linux/amd64 please ?

**Comment by Nick1st** [comment]
# FancyVideo-API - Notice of Discontinuance
As of today, Friday, Feburary the 12th 2024 **FancyVideo-API is officially discontinued immediately**. I'm deeply sorry for all inconveniences this causes.

## Why?
I didn't make this decision light-hearted. FV-API started as a research and tech demo project. As such, the project wasn't well planed, the tech used by it was a bunch of buggy hacks, held together by loose amounts of duct-tape. That luckily got better within the first versions, however the API did never reach a level that I was satisfied with. Because of that I started a rewrite about one years ago, but due to a series of unlucky events this project stalled. Despite simply forward porting the legacy API would've been a task of hours, I decided against it. During the rewrite I was beaten time and time again to the conclusion that several layers of the API were flawed from the grounds up. That further stalled progress, and also was the reason why I didn't simply continue forward porting. During the two years I maintained FV-API, I got a much better understanding of how things work, and how they should've be done instead. 
FV-API started as a tech demo/research project and I must admit that that's all it ever was. With the knowledge I have today, I probably wouldn't have published the project on CurseForge for others to use, the project was not ready for that (nor meant for it in the beginning). I think FV still reached the goal it was originally  created for: showing whats technically possible and getting others to build upon the idea.

## What does this mean?
FV-API will no longer receive updates (This includes critical bugfixes and security updates). If you're using FV-API as a library, you should move on (simply read on for more details).

## What should I do (Modder)
I do not want to recommend a specific project, however here are two projects that I came along over the last year:
- [WATERMeDIA: Multimedia API](https://www.curseforge.com/minecraft/mc-mods/watermedia) by SrRapero720
- [A fork](https://github.com/BehindTheScenery/FancyVideo-API) by BehindTheScenery

## What's going to happen with this discord server?
I'll put this server in read-only mode until there is something new from me.
I'm still interested in the project, and I've recently been obsessed with Gstreamer. Maybe one day there will be FV-2.0 (probably as a tech demo only though!).


I just want to thank everybody who used FV-API over the last two years. I should've probably done this step half a year earlier, but I just wanted to (personally) feel sure that this is the right decision. I simply do no longer have the time required to maintain this project due to things that changed in my personal life. Thanks again for using FV-API. I hope you all stay well.
